server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://team6-prod-db.coa6rnrmkwmp.ap-northeast-2.rds.amazonaws.com:3306/maindb?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: master
    password: withaPPly**
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql   # mysql ??
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      show_sql: true          # ??????? ??? ?? SQL?? ??? ??
      format_sql: true        # SQL?? ??? ?? ??
      use_sql_comments: true  # ??? ?? ??
# ?? ??
logging.level:
  org.hibernate: debug
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  org.springframework.web: DEBUG